version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./templates:/app/templates
      - ./static:/app/static
      - ./logs:/app/logs  # Add this line to mount the logs directory
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--no-reload"]
